qq_music:
  - main_url: "https://y.qq.com/"

login:
  qrcode:
    url: "https://ssl.ptlogin2.qq.com/ptqrshow"
    parameter:
      - appid: 716027609
      - e: 2
      - l: "M"
      - s: 3
      - d: 72
      - v: 4
      - t: null
      - daid: 383
      - pt_3rd_aid: 100497308
